# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'alarmas-windowCwyaxX.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QDialogButtonBox,
    QFrame, QLabel, QLineEdit, QSizePolicy, QHBoxLayout,QComboBox,QVBoxLayout,QSpinBox,
    QWidget)

class Ui_SubVentAlarmas(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1059, 642)
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 1041, 621))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.layoutWidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.buttonBox = QDialogButtonBox(self.frame_2)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(800, 570, 191, 23))
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(370, 10, 251, 39))
        font = QFont()
        font.setFamily(u"Sylfaen")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(40, 70, 951, 491))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 140, 141, 41))
        self.label_3.setFont(font)
        self.ip_final = QLineEdit(self.frame_3)
        self.ip_final.setObjectName(u"ip_final")
        self.ip_final.setGeometry(QRect(180, 150, 51, 21))
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 70, 121, 41))
        self.label_5.setFont(font)
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 261, 51))
        self.label_2.setFont(font)
        self.label_4 = QLabel(self.frame_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 210, 121, 51))
        self.label_4.setFont(font)
        self.checkBox_7 = QCheckBox(self.frame_3)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(380, 10, 61, 41))
        self.checkBox_11 = QCheckBox(self.frame_3)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(490, 10, 51, 41))
        self.checkBox_11.setStyleSheet(
            u"self.checkBox.setStyleSheet(\"QCheckBox::indicator { width: 20px; height: 20px; border: 1px solid black; }\")\n"
            "")
        self.ip_final_2 = QLineEdit(self.frame_3)
        self.ip_final_2.setObjectName(u"ip_final_2")
        self.ip_final_2.setGeometry(QRect(180, 220, 51, 21))
        self.checkBox_8 = QCheckBox(self.frame_3)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(380, 140, 61, 41))
        self.checkBox_9 = QCheckBox(self.frame_3)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(490, 140, 61, 41))
        self.checkBox_10 = QCheckBox(self.frame_3)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(590, 140, 61, 41))
        self.checkBox_12 = QCheckBox(self.frame_3)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(690, 140, 61, 41))
        self.checkBox_13 = QCheckBox(self.frame_3)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(790, 140, 101, 41))
        self.checkBox_14 = QCheckBox(self.frame_3)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(380, 210, 61, 41))
        self.checkBox_16 = QCheckBox(self.frame_3)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(590, 210, 61, 41))
        self.checkBox_17 = QCheckBox(self.frame_3)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setGeometry(QRect(690, 210, 61, 41))
        self.checkBox_18 = QCheckBox(self.frame_3)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setGeometry(QRect(790, 210, 101, 41))
        self.comboBox = QComboBox(self.frame_3)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(180, 80, 91, 21))
        self.checkBox_19 = QCheckBox(self.frame_3)
        self.checkBox_19.setObjectName(u"checkBox_19")
        self.checkBox_19.setGeometry(QRect(380, 70, 61, 41))
        self.checkBox_20 = QCheckBox(self.frame_3)
        self.checkBox_20.setObjectName(u"checkBox_20")
        self.checkBox_20.setGeometry(QRect(490, 70, 61, 41))
        self.checkBox_21 = QCheckBox(self.frame_3)
        self.checkBox_21.setObjectName(u"checkBox_21")
        self.checkBox_21.setGeometry(QRect(590, 70, 61, 41))
        self.checkBox_22 = QCheckBox(self.frame_3)
        self.checkBox_22.setObjectName(u"checkBox_22")
        self.checkBox_22.setGeometry(QRect(690, 70, 61, 41))
        self.checkBox_23 = QCheckBox(self.frame_3)
        self.checkBox_23.setObjectName(u"checkBox_23")
        self.checkBox_23.setGeometry(QRect(790, 70, 91, 41))
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 280, 151, 61))
        self.label_6.setFont(font)
        self.ip_final_3 = QLineEdit(self.frame_3)
        self.ip_final_3.setObjectName(u"ip_final_3")
        self.ip_final_3.setGeometry(QRect(180, 300, 51, 21))
        self.checkBox_24 = QCheckBox(self.frame_3)
        self.checkBox_24.setObjectName(u"checkBox_24")
        self.checkBox_24.setGeometry(QRect(380, 290, 61, 41))
        self.checkBox_25 = QCheckBox(self.frame_3)
        self.checkBox_25.setObjectName(u"checkBox_25")
        self.checkBox_25.setGeometry(QRect(490, 290, 61, 41))
        self.checkBox_26 = QCheckBox(self.frame_3)
        self.checkBox_26.setObjectName(u"checkBox_26")
        self.checkBox_26.setGeometry(QRect(590, 290, 61, 41))
        self.checkBox_27 = QCheckBox(self.frame_3)
        self.checkBox_27.setObjectName(u"checkBox_27")
        self.checkBox_27.setGeometry(QRect(690, 290, 61, 41))
        self.checkBox_28 = QCheckBox(self.frame_3)
        self.checkBox_28.setObjectName(u"checkBox_28")
        self.checkBox_28.setGeometry(QRect(790, 290, 101, 41))
        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 360, 161, 61))
        self.label_7.setFont(font)
        self.checkBox_29 = QCheckBox(self.frame_3)
        self.checkBox_29.setObjectName(u"checkBox_29")
        self.checkBox_29.setGeometry(QRect(380, 370, 61, 41))
        self.checkBox_30 = QCheckBox(self.frame_3)
        self.checkBox_30.setObjectName(u"checkBox_30")
        self.checkBox_30.setGeometry(QRect(490, 370, 61, 41))
        self.checkBox_31 = QCheckBox(self.frame_3)
        self.checkBox_31.setObjectName(u"checkBox_31")
        self.checkBox_31.setGeometry(QRect(590, 370, 61, 41))
        self.checkBox_32 = QCheckBox(self.frame_3)
        self.checkBox_32.setObjectName(u"checkBox_32")
        self.checkBox_32.setGeometry(QRect(690, 370, 61, 41))
        self.checkBox_33 = QCheckBox(self.frame_3)
        self.checkBox_33.setObjectName(u"checkBox_33")
        self.checkBox_33.setGeometry(QRect(790, 370, 101, 41))
        self.label_9 = QLabel(self.frame_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 430, 151, 51))
        self.label_9.setFont(font)
        self.checkBox_34 = QCheckBox(self.frame_3)
        self.checkBox_34.setObjectName(u"checkBox_34")
        self.checkBox_34.setGeometry(QRect(380, 430, 61, 41))
        self.checkBox_35 = QCheckBox(self.frame_3)
        self.checkBox_35.setObjectName(u"checkBox_35")
        self.checkBox_35.setGeometry(QRect(490, 430, 61, 41))
        self.checkBox_36 = QCheckBox(self.frame_3)
        self.checkBox_36.setObjectName(u"checkBox_36")
        self.checkBox_36.setGeometry(QRect(590, 430, 61, 41))
        self.checkBox_37 = QCheckBox(self.frame_3)
        self.checkBox_37.setObjectName(u"checkBox_37")
        self.checkBox_37.setGeometry(QRect(690, 430, 61, 41))
        self.checkBox_38 = QCheckBox(self.frame_3)
        self.checkBox_38.setObjectName(u"checkBox_38")
        self.checkBox_38.setGeometry(QRect(790, 430, 101, 41))
        self.checkBox_39 = QCheckBox(self.frame_3)
        self.checkBox_39.setObjectName(u"checkBox_39")
        self.checkBox_39.setGeometry(QRect(490, 210, 61, 41))
        self.frame_4 = QFrame(self.frame_3)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(350, 60, 561, 421))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.raise_()
        self.label_3.raise_()
        self.ip_final.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.checkBox_7.raise_()
        self.checkBox_11.raise_()
        self.ip_final_2.raise_()
        self.comboBox.raise_()
        self.label_6.raise_()
        self.ip_final_3.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.checkBox_19.raise_()
        self.checkBox_20.raise_()
        self.checkBox_21.raise_()
        self.checkBox_22.raise_()
        self.checkBox_23.raise_()
        self.checkBox_8.raise_()
        self.checkBox_9.raise_()
        self.checkBox_10.raise_()
        self.checkBox_12.raise_()
        self.checkBox_13.raise_()
        self.checkBox_14.raise_()
        self.checkBox_16.raise_()
        self.checkBox_17.raise_()
        self.checkBox_18.raise_()
        self.checkBox_24.raise_()
        self.checkBox_25.raise_()
        self.checkBox_26.raise_()
        self.checkBox_27.raise_()
        self.checkBox_28.raise_()
        self.checkBox_29.raise_()
        self.checkBox_30.raise_()
        self.checkBox_31.raise_()
        self.checkBox_32.raise_()
        self.checkBox_33.raise_()
        self.checkBox_34.raise_()
        self.checkBox_35.raise_()
        self.checkBox_36.raise_()
        self.checkBox_37.raise_()
        self.checkBox_38.raise_()
        self.checkBox_39.raise_()

        self.horizontalLayout_5.addWidget(self.frame_2)

        self.horizontalLayout_6.addWidget(self.frame)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)

    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Configuracion de Alarmas", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Umbral de Tinta", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Estado", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Habilitar Alertas de Escritorio", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Contadores", None))
        self.checkBox_7.setText(QCoreApplication.translate("Form", u"Si", None))
        self.checkBox_11.setText(QCoreApplication.translate("Form", u" No", None))
        self.checkBox_8.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_9.setText(QCoreApplication.translate("Form", u"Alto", None))
        self.checkBox_10.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_12.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_13.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.checkBox_14.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_16.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_17.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_18.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.comboBox.setItemText(0, "")
        self.comboBox.setItemText(1, QCoreApplication.translate("Form", u"Other", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Form", u"Unknow", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Form", u"Idle", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Form", u"Printing", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("Form", u"Warmup", None))

        self.checkBox_19.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_20.setText(QCoreApplication.translate("Form", u"Alto", None))
        self.checkBox_21.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_22.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_23.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Papel en Bandeja", None))
        self.checkBox_24.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_25.setText(QCoreApplication.translate("Form", u"Alto", None))
        self.checkBox_26.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_27.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_28.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Atasco de Papel", None))
        self.checkBox_29.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_30.setText(QCoreApplication.translate("Form", u"Alto", None))
        self.checkBox_31.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_32.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_33.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Tapa Abierta", None))
        self.checkBox_34.setText(QCoreApplication.translate("Form", u"Critico", None))
        self.checkBox_35.setText(QCoreApplication.translate("Form", u"Alto", None))
        self.checkBox_36.setText(QCoreApplication.translate("Form", u"Medio", None))
        self.checkBox_37.setText(QCoreApplication.translate("Form", u"Bajo", None))
        self.checkBox_38.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n", None))
        self.checkBox_39.setText(QCoreApplication.translate("Form", u"Alto", None))
    # retranslateUi


class AlarmaWidget(QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_SubVentAlarmas()
        self.ui.setupUi(self)